/**
 * DiamondJS Hello World Example
 *
 * This example demonstrates the DiamondJS runtime and component system.
 * Templates are compiled at build time by the Parcel transformer.
 */

import { DiamondCore, Component } from '@diamondjs/runtime'

// Import compiled template - demonstrates the Parcel transformer
import * as CounterTemplateModule from './Counter.diamond.html'

/**
 * Counter Component
 *
 * This version uses a template compiled by the Parcel transformer.
 */
class Counter extends Component {
  state = DiamondCore.reactive({ count: 0 })

  increment(): void {
    this.state.count++
  }

  decrement(): void {
    this.state.count--
  }

  // Use the compiled template from the .diamond.html file
  static createTemplate = CounterTemplateModule.createTemplate
}

/**
 * Greeting Component
 *
 * Demonstrates:
 * - Two-way input binding
 * - Text interpolation
 *
 * In production, this would also use a compiled template.
 */
class Greeting extends Component {
  state = DiamondCore.reactive({ name: 'World' })

  // In production, this would be generated by the compiler from:
  // <div class="greeting">
  //   <input value.bind="name" placeholder="Enter your name">
  //   <p>Hello, ${name}!</p>
  // </div>
  static createTemplate() {
    return (vm: Greeting) => {
      const div = document.createElement('div')
      div.className = 'greeting'

      const input = document.createElement('input')
      input.placeholder = 'Enter your name'
      DiamondCore.bind(
        input,
        'value',
        () => vm.state.name,
        (v) => (vm.state.name = v as string)
      )

      const p = document.createElement('p')
      DiamondCore.bind(p, 'textContent', () => `Hello, ${vm.name}!`)

      div.appendChild(input)
      div.appendChild(p)

      return div
    }
  }
}

// Mount the components
const app = document.getElementById('app')!

const counterTitle = document.createElement('h2')
counterTitle.textContent = 'Counter (Compiled Template)'
app.appendChild(counterTitle)

const counter = new Counter()
counter.mount(app)

const greetingTitle = document.createElement('h2')
greetingTitle.textContent = 'Greeting'
app.appendChild(greetingTitle)

const greeting = new Greeting()
greeting.mount(app)

// Log to console for debugging
console.log('DiamondJS Hello World loaded!')
console.log('Counter component (compiled template):', counter)
console.log('Greeting component:', greeting)
